### ISSUE TITLE
caffe models 

### ISSUE THREAD

**Issue by cnu1439** [superxuang/caffe_3d_faster_rcnn#15]
Hi,
   where can I download pre trained models for organ localisation for CT images. 
Thanks,
Srinivas.

**Comment by superxuang** [comment]
Sorry, the model file is too big, so I did not upload it.

**Comment by cnu1439** [comment]
Hi, 
Can you share them through g-drive or some other medium.
Thanks,
Srinivas.

**Comment by superxuang** [comment]
Hi, please find the model files through this link:
https://www.dropbox.com/s/v8d3qpyfurlhpc3/organ_localization_models.zip?dl=0

**Comment by cnu1439** [comment]
Thank you so much.
